on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [12.16.2]
        terraform-version: [0.12.24, 0.11.14]
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker --version



