name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - { NODE_VERSION: 12.16.2, TERRAFORM_VERSION: 0.12.24 }
          - { NODE_VERSION: 12.16.2, TERRAFORM_VERSION: 0.11.14 }
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker --version



