name: Master CI Pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        terraform-version: [0.12.29, 0.12.24, 0.11.14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t fenrirwillow/build-util-images --build-arg node_version=${{ matrix.node-version }} --build-arg terraform_version=${{ matrix.terraform-version }} .

      - name: Docker Tag
        run: docker tag fenrirwillow/build-util-images fenrirwillow/build-util-images:node-${{ matrix.node-version }}-terraform-${{ matrix.terraform-version }}

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Push
        run: docker push fenrirwillow/build-util-images:node-${{ matrix.node-version }}-terraform-${{ matrix.terraform-version }}
