name: Pull Request Pipeline

on:
  pull_request:
    branches:
      - '**'
    types:
      ['opened', 'reopened', 'reopened']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        terraform-version: [0.12.29, 0.12.24, 0.11.14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t fenrirwillow/build-util-images --build-arg node_version=${{ matrix.node-version }} --build-arg terraform_version=${{ matrix.terraform-version }} .
